### ISSUE TITLE
Implement a Generic Profile Page with Achievements and Stats

### ISSUE THREAD

**Issue by ClanCo** [z-korp/zkube#23] opened 2024-08-22 10:18 UTC
#### **Description**
We need to add a new generic profile page to our application using the Shadcn component library. This profile page should include sections for user achievements and game statistics (such as the number of games played, average points per game, total points, etc.). Additionally, users should be able to filter their statistics by season. The profile page should be designed in a way that allows for easy customization in the future.

While we provide an example layout for inspiration, developers are encouraged to use their creativity and imagination as long as the final design is visually coherent and consistent with the rest of the application's design language.

#### **Tasks**
1. **Set Up Profile Page Structure:**
   - Create a new `ProfilePage` component in the `pages` directory.
   - Use Shadcn components to ensure the design aligns with our existing UI framework.

2. **Achievements Section:**
   - Add a section to display user achievements.
   - Utilize Shadcn cards or similar components to showcase each achievement.
   - Ensure this section is responsive and visually consistent with the rest of the page.

3. **Statistics Section:**
   - Add a section to display various game stats.
   - Display key statistics such as:
     - Number of games played
     - Average points per game
     - Total points
     - Total wins
   - Implement a dropdown or tab system using Shadcn components to allow users to filter stats by season.

4. **Filtering and Sorting:**
   - Implement filtering and sorting mechanisms for the stats section.
   - Allow sorting by various criteria like date, points, or number of games.
   - Ensure filtering by season works seamlessly and updates the stats in real time.

5. **Responsive Design:**
   - Ensure the entire profile page is responsive and works well on different screen sizes.
   - Test the layout on mobile, tablet, and desktop views.

6. **Customizability:**
   - Design the page structure to allow for easy future customizations.
   - Ensure that additional sections or features can be added with minimal changes to the existing codebase.

7. **Testing:**
   - Write unit tests for the new `ProfilePage` component and its sub-components.
   - Ensure all functionalities like filtering, sorting, and stats display are covered in the tests.

8. **Documentation:**
   - Update the project’s documentation to include details about the new profile page.
   - Add instructions on how to extend or customize the page in the future.

#### **Acceptance Criteria**
- A new `ProfilePage` component exists and integrates seamlessly with the existing app.
- The profile page displays user achievements and stats.
- Users can filter and sort stats by season and other criteria.
- The page is fully responsive and works across different devices.
- The page structure is designed to allow easy future customizations.
- Developers have the freedom to design the page creatively, as long as the final output is visually coherent.
- All new components and features are fully tested and documented.

![Stats](https://github.com/user-attachments/assets/5004ad6c-e6e5-4d83-9266-93503324fbae)

**Comment by estherbreath** [comment] 2024-08-22 10:53
@ClanCo I would like to work on this issue, please

**Comment by Cheelax** [comment] 2024-08-22 11:25
Hi everyone.
There is a new process for the ODHack, now you must apply to the tasks directly from Onlydust: https://app.onlydust.com/hackathons/odhack-70
We will only look at application made via this process.

**Comment by ooochoche** [comment] 2024-08-22 11:50
@ClanCo can I work on this

**Comment by Iwueseiter** [comment] 2024-08-22 11:52
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hi can  work on this?

**Comment by ooochoche** [comment] 2024-08-22 11:52
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
I am a frontend and a web3 developer

**Comment by raizo07** [comment] 2024-08-22 11:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
I'll like to be assigned to work on this.

**Comment by LukePereyra** [comment] 2024-08-22 11:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
hey team, I will like to work on this one! I already have experience Shadcn library and React. I'm a Frontend Engineer doing my firsts steps in web3.


### How I plan on tackling this issue
the tasks are self-descriptive, I will follow it as expected.

**Comment by ShantelPeters** [comment] 2024-08-22 12:02
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
To answer the application form question, you can emphasize your experience as a frontend developer with expertise in JavaScript and UI frameworks, and how it relates to the tasks outlined in the job description. Here’s a tailored response:

---

As a frontend developer with strong experience in JavaScript and UI component libraries like Shadcn, I am well-prepared to tackle the challenge of building a new generic profile page for your application. My background includes working on complex UI structures, implementing responsive designs, and ensuring seamless integration with existing frameworks, all of which are essential for this project.

### Relevant Experience:

1. **Proficiency in JavaScript**: My expertise in JavaScript enables me to efficiently create interactive and dynamic features such as filtering, sorting, and real-time updates, which are crucial for the statistics section of the profile page. I am comfortable using modern JavaScript frameworks and libraries to enhance user experience and performance.

2. **Experience with UI Component Libraries**: I have worked extensively with component libraries similar to Shadcn, where I’ve designed and implemented various UI components such as cards, dropdowns, and tabs. My experience allows me to create visually consistent and reusable components that align with the overall design language of the application.

3. **Responsive Design**: Ensuring that web pages are responsive and work well across all devices is a key aspect of my work. I have successfully delivered projects where responsive design was a critical requirement, ensuring a smooth user experience on mobile, tablet, and desktop devices.

4. **Customizability and Future-Proofing**: I understand the importance of designing flexible and easily customizable components. My approach to building the ProfilePage would involve creating a structure that can be easily extended in the future, allowing for additional features or sections to be added with minimal code changes.

5. **Testing and Documentation**: I am thorough in writing unit tests to cover all functionalities, ensuring that the ProfilePage and its components are robust and reliable. Additionally, I prioritize clear documentation to guide future developers in extending or customizing the page.

### How My Background Will Be Leveraged:

- **Setting Up the Profile Page**: I will efficiently structure the ProfilePage component using Shadcn components, ensuring that it integrates seamlessly with your existing application. My attention to detail will ensure that each section—achievements and statistics—functions as intended and aligns with the overall design.

- **Implementing Functionality**: Leveraging my JavaScript skills, I will implement filtering, sorting, and real-time updating mechanisms in the stats section, ensuring users have a smooth and interactive experience when viewing their game statistics.

- **Ensuring Customizability**: My experience with modular and component-based design will ensure that the profile page is not only functional but also easy to customize and extend in the future, meeting your long-term project goals.

My combination of technical skills, experience in UI design, and commitment to delivering high-quality, responsive, and customizable solutions make me a strong candidate to contribute effectively to your team and successfully build the new profile page.

### How I plan on tackling this issue
To approach the task of creating a new generic profile page using the Shadcn component library, I would break down the problem into clear, manageable steps, focusing on structure, functionality, design consistency, and future-proofing. Here's how I would approach it:

### 1. **Understanding the Requirements**
   - **Review the Example Layout**: Start by analyzing the provided layout for inspiration and understanding the required components, their arrangement, and the overall aesthetic.
   - **Familiarize with Shadcn Components**: Review the Shadcn component library to identify the components that best fit the requirements (e.g., cards for achievements, dropdowns for filtering stats).

### 2. **Set Up the Profile Page Structure**
   - **Create the ProfilePage Component**:
     - Set up a new `ProfilePage` component in the `pages` directory.
     - Use Shadcn layout components (e.g., containers, grids, flexboxes) to structure the page into distinct sections for achievements and statistics.
   - **Integrate Global Styles**:
     - Ensure that the new page inherits the global styling rules for consistency with the rest of the application.
     - Incorporate any necessary CSS or theme settings from Shadcn to maintain visual coherence.

### 3. **Implement the Achievements Section**
   - **Display User Achievements**:
     - Use Shadcn cards or similar components to create individual achievement displays.
     - Ensure that this section is responsive by utilizing CSS flexbox or grid layouts.
     - Consider adding hover effects, animations, or other visual cues to enhance user interaction.
   - **Ensure Consistency**:
     - Match the design language of the cards with the rest of the application, ensuring the fonts, colors, and spacing are aligned.

### 4. **Implement the Statistics Section**
   - **Display Game Statistics**:
     - Create a structured display for key statistics (e.g., number of games played, average points per game, total points, total wins).
     - Use Shadcn components such as tables, lists, or grids for an organized presentation.
   - **Add Filtering and Sorting**:
     - Implement a dropdown or tab system using Shadcn components to allow users to filter stats by season.
     - Ensure sorting by various criteria (date, points, number of games) is intuitive and updates the stats in real time.
     - Optimize performance by using debouncing or other techniques to handle real-time updates smoothly.

### 5. **Ensure Responsive Design**
   - **Responsive Layout**:
     - Utilize media queries and Shadcn's responsive utilities to ensure the profile page adapts well to different screen sizes (mobile, tablet, desktop).
     - Test the page on various devices to ensure it looks good and functions correctly across all viewports.
   - **Accessible Design**:
     - Ensure the design is accessible, with appropriate text sizes, contrast ratios, and touch targets for mobile users.

### 6. **Design for Future Customizations**
   - **Modular and Extendable Structure**:
     - Create the page structure in a modular way, allowing new sections or features to be added with minimal impact on existing code.
     - Use reusable components where possible, such as creating a generic card component for achievements that can be easily customized or extended.
   - **Document Customization Options**:
     - Clearly document the design choices and how new features can be integrated in the future.

### 7. **Testing**
   - **Unit Testing**:
     - Write comprehensive unit tests for the `ProfilePage` component and its sub-components to ensure functionality such as filtering, sorting, and stats display works correctly.
   - **End-to-End Testing**:
     - Perform end-to-end tests to simulate user interactions, ensuring that all features work as expected across different devices and scenarios.

### 8. **Documentation**
   - **Update Project Documentation**:
     - Document the new `ProfilePage` component, including how to extend or customize it.
     - Provide clear instructions on the component structure, CSS classes used, and how the filtering and sorting mechanisms are implemented.

### 9. **Final Review and Deployment**
   - **Code Review**:
     - Perform or request a code review to ensure that the implementation meets the project’s standards and requirements.
   - **Deploy and Monitor**:
     - Deploy the new profile page to a staging environment, monitor its performance, and gather feedback for any final adjustments before moving to production.

**Comment by coxmars** [comment] 2024-08-22 12:16
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hi @ClanCo, I'm a software developer with over 2 years of experience working with Java, C#, Dart, and other technologies. I'm an active member of the Dojo Coding community in Costa Rica, and I've contributed in different project for the OdHack in the past and also I already have experience with Cairo and this frontend tech stack.

### How I plan on tackling this issue
My approach:

- Profile Page Setup: Create a new ProfilePage component using Shadcn, ensuring it's consistent with the app’s design.

- Achievements and Stats: Implement sections for user achievements and game stats, using Shadcn components for responsiveness.

- Filtering and Responsiveness: Add filtering by season and ensure the page is fully responsive across all devices.

- Customizability: Design with future customizations in mind, keeping the structure modular and maintainable.

- Testing and Documentation: Write unit tests for key components and update documentation for future enhancements.

Thanks for considering my application.

**Comment by carldouch** [comment] 2024-08-22 13:05
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
Hey, I'm a frontend developer with a strong background in backend development, particularly in Java. After building solid backend systems, I transitioned to frontend work, focusing on creating user-friendly interfaces, seamless user experiences, and experimenting with 3D using Three.js. This combination of skills allows me to have a comprehensive understanding of the full stack, ensuring my frontend work is well-integrated with the backend.

### How I plan on tackling this issue
To tackle this task, I'll start by setting up the basic structure of the ProfilePage using Shadcn components, ensuring it aligns with the existing UI. I'll create distinct sections for achievements and game statistics, utilizing cards for achievements and implementing filtering and sorting mechanisms for stats by season. The design will be fully responsive across devices. I'll write unit tests to ensure all functionalities work as expected and document the process for easy future customizations. This approach ensures a clean, maintainable, and flexible solution.

**Comment by ScottyDavies** [comment] 2024-08-22 13:07
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkube).

### My background and how it can be leveraged
As a frontend developer, I have experience building responsive and user-friendly web applications using modern JavaScript frameworks like React, Next.js, and Vue.js. I'm proficient in working with component-based architectures and UI libraries, which will be highly beneficial for this project.

### How I plan on tackling this issue
To approach this problem, I would follow these steps:

Set up the ProfilePage component:
Create a new ProfilePage component in the pages directory.
Import and use the necessary Shadcn components to ensure the design aligns with the existing UI framework.
Implement the Achievements Section:
Add a section to display the user's achievements.
Utilize Shadcn cards or similar components to showcase each achievement.
Ensure the section is responsive and visually consistent with the rest of the page.
Implement the Statistics Section:
Add a section to display the user's game statistics.
Display the key statistics like number of games played, average points per game, total points, and total wins.
Implement a dropdown or tab system using Shadcn components to allow users to filter stats by season.
Implement Filtering and Sorting:
Implement filtering and sorting mechanisms for the stats section.
Allow sorting by various criteria like date, points, or number of games.
Ensure filtering by season works seamlessly and updates the stats in real time.
Ensure Responsive Design:
Ensure the entire profile page is responsive and works well on different screen sizes.
Test the layout on mobile, tablet, and desktop views.
Design for Customizability:
Design the page structure to allow for easy future customizations.
Ensure that additional sections or features can be added with minimal changes to the existing codebase.
Write Tests:
Write unit tests for the new ProfilePage component and its sub-components.
Ensure all functionalities like filtering, sorting, and stats display are covered in the tests.
Document the Changes:
Update the project's documentation to include details about the new profile page.
Add instructions on how to extend or customize the page in the future.

**Closed** 2024-09-04 19:43 UTC
Labels: ODHack7
